# SPDX-FileCopyrightText: Â© 2023-2025 Nikita Karamov <me@kytta.dev>
# SPDX-License-Identifier: CC0-1.0

[build]
  command = "pnpm run build"
  publish = "dist"
[dev]
  command = "pnpm dev"
  targetPort = 4321
